blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Grayjay Community Discussion
    url: https://github.com/futo-org/grayjay-sources/discussions
    about: Join the community discussion for questions and general topics
  - name: ðŸ“– Documentation
    url: https://github.com/futo-org/grayjay-sources
    about: Check out the documentation for guides and information
